[package]
name = "r-snake"
version = "0.1.0"
authors = ["Edwin Chebii <https://edcheyjr.github.io/my-portfolio/>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies] 
rand = "0.8.5"
piston_window = "0.128.0" 